Ci
tavisca-vjola/web_api pull request #4
Opened 2019-08-20 10:58 UTC by tavisca-vjola

@Ashwarya-Tavisca

Added both ci and cd in single jenkins file

2019-10-07 15:51 UTC, tavisca-vjola commented
@tavisca-tgoyal 
please review my code

2019-10-07 15:54 UTC, tavisca-tgoyal requested changes

2019-10-07 15:54 UTC, tavisca-tgoyal commented on Dockerfile
> +#ENTRYPOINT ["dotnet", "${MYFILENAME}.dll"]
I am tavisca t goyal bayi

2019-10-07 15:56 UTC, tavisca-vjola commented
please review my code
@tavisca-tgoyal

2019-10-07 16:07 UTC, tavisca-vjola commented
please review my code @tavisca-tgoyal

2019-10-07 16:09 UTC, tavisca-tgoyal requested changes

2019-10-07 16:09 UTC, tavisca-tgoyal commented on Jenkinsfile
> +       password(name: 'DOCKER_PASSWORD', defaultValue: 'Jola@1998', description: 'Enter Password')
please dont  use it buddy

2019-10-08 13:35 UTC, tavisca-vjola commented
please add this file @tavisca-tgoyal

2019-10-09 03:43 UTC, tavisca-vjola commented
please review@tavisca-spanda

2019-10-09 03:44 UTC, tavisca-vjola commented
please review @tavisca-spanda

2019-10-09 03:45 UTC, tavisca-spanda reviewed
Here it is

2019-10-09 03:45 UTC, tavisca-spanda commented on Dockerfile
>  FROM microsoft/dotnet:2.2-aspnetcore-runtime-nanoserver-1803 AS base
I saw

2019-10-09 03:52 UTC, tavisca-spanda reviewed
See the comment

2019-10-09 03:52 UTC, tavisca-spanda commented on Jenkinsfile
> +       password(name: 'DOCKER_PASSWORD', defaultValue: 'Jola@1998', description: 'Enter Password')
Don't do this.

2019-10-09 05:16 UTC, tavisca-vjola commented
Please comment please

2019-10-09 05:16 UTC, tavisca-vjola commented
comment @tavisca-spanda

2019-10-09 05:17 UTC, tavisca-spanda commented on Dockerfile
> +#ENTRYPOINT ["dotnet", "${MYFILENAME}.dll"]
Dekh lo

2019-10-09 05:18 UTC, tavisca-spanda reviewed
check it

2019-10-09 05:18 UTC, tavisca-spanda commented on Jenkinsfile
> -       string(name: 'DOCKER_PASSWORD', defaultValue: 'Jola@1998', description: 'Enter Password')
I concur

2019-10-23 05:02 UTC, closed without merging